version: "2"

services:
  devkit:
    image: devkitpro/devkita64:latest
    volumes:
      - ".:/advent-of-code-nx"
    command: bash -c "dkp-pacman -Syu --noconfirm && cd /advent-of-code-nx && make -j8"